apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: coredns
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        kubernetes cluster.local 10.96.0.0/12 {
          pods insecure
        }
        auto backend {
          directory /zones
        }
        prometheus
        proxy . 10.211.55.1:53
        cache 30
    }